networks:
  default:

volumes:
  image_hosting_data:

services:
  app:
    container_name: app
    build: ./app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./images:/app/images
      - ./static:/app/static
    networks:
      - default
    depends_on:
      - db

  nginx:
    container_name: nginx
    command: nginx -g "daemon off;"
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./images:/images
      - ./static:/etc/nginx/html
      - ./logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
    depends_on:
      - app

  db:
    image: postgres:latest
    container_name: db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - image_hosting_data:/var/lib/postgresql/data
    networks:
      - default
    restart: always